format="$all"

add_newline = true

[character]
success_symbol = "[λ](bold green) "
error_symbol = "[✗](bold red) "
vicmd_symbol = "[V](bold green) "

[time]
disabled = true
format = '[\[ $time \]]($style) '
time_format = "%H:%M"
utc_time_offset = "+1"
