#!/bin/sh
#
# musl-clang: A clang wrapper for musl C library.
#             Supports static linking. (-static)
#
# WARNING: This is not a perfect drop-in replacement
#
# See LICENSE file for copyright and license details.
#

PREFIX=${MUSL_PREFIX:-"x86_64-linux-musl"}
LIBPREFIX=/usr/lib/${PREFIX}
INCPREFIX=/usr/include/${PREFIX}

if [ ! -d "${LIBPREFIX}" ]; then
	echo "invalid prefix: ${LIBPREFIX}"
	return 1
fi

CPP=no
case "$0" in
	*++) CPP=yes ;;
esac

if [ "${CPP}" = "yes" ]; then
	CLANG=${REALCLANGPP:-"clang++"}
else
	CLANG=${REALCLANG:-"clang"}
fi

hasNo() {
	pat="$1"
	shift 1

	for e in "$@"; do
		if [ "$e" = "${pat}" ]; then
			return 1
		fi
	done
	return 0
}

ARGS="-nostdinc"
TAIL=""

if hasNo '-nostdinc' "$@"; then
	ARGS="${ARGS} -isystem ${INCPREFIX}"
fi

if \
	hasNo '-c' "$@" && \
	hasNo '-S' "$@" && \
	hasNo '-E' "$@"
then
	ARGS="${ARGS} -nostdlib"
	ARGS="${ARGS} -Wl,-dynamic-linker=${LIBPREFIX}/libc.so"
	ARGS="${ARGS} -L${LIBPREFIX}"
	#ARGS="${ARGS} -Wl,-rpath=${LIBPREFIX}"

	if hasNo '-nostartfiles' "$@" && \
	   hasNo '-nostdlib' "$@" && \
	   hasNo '-nodefaultlibs' "$@"
	then
		ARGS="${ARGS} ${LIBPREFIX}/crt1.o"
		ARGS="${ARGS} ${LIBPREFIX}/crti.o"

		TAIL="${TAIL} ${LIBPREFIX}/crtn.o"
	fi

	if hasNo '-nostdlib' "$@" && \
	   hasNo '-nodefaultlibs' "$@"
	then
		if [ "${CPP}" = "yes" ]; then
			TAIL="${TAIL} -lc++"
			TAIL="${TAIL} -lunwind"
			TAIL="${TAIL} -lm"
		fi
		TAIL="${TAIL} -lc"
		#TAIL="${TAIL} -Wl,-Bstatic -lcompiler_rt"
	fi
fi

#echo "# $0" "$@" >&2
#set -x
exec ${CLANG} ${ARGS} "$@" ${TAIL}
