#!/usr/bin/env Rscript
# Create a stem plot, pass column to extract from csv
args <- commandArgs(trailingOnly = TRUE)
column <- args[1]
stopifnot(column != "")

csvfile <- readLines(file("stdin"))
df <- read.csv(text = csvfile, header = TRUE)
a <- df[, column]
scale <- if (length(args) >= 2) as.numeric(args[2]) else 1
stem(a, scale)
